import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import { getCurrentSession } from "@/actions/auth";
import { SanityLive } from "@/sanity/lib/live";
import HeaderCategorySelector from "@/components/layout/HeaderCategorySelector";
import Cart from "@/components/cart/Cart";
import Script from "next/script";
import { Suspense } from "react";
import AnalyticsTracker from "@/components/layout/AnalyticsTracker";
import Footer from "@/components/layout/Footer";
import { ThemeContextProvider } from "@/components/Contexts/ThemeContext";
import Theme from "@/components/Theme/Theme";
import ScrollToTopButton from "@/components/layout/ScrollToTopButton";
import { I18nProviderClient } from "@/components/Contexts/I18nProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const { user } = await getCurrentSession();

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased min-h-[125vh] transition-colors`}
      >
        <I18nProviderClient>
          <ThemeContextProvider>
            <Header user={user} categorySelector={<HeaderCategorySelector />} />

            <Script
              src="https://cloud.umami.is/script.js"
              data-website-id="(YOUR UMAMI WEBSITE ID)"
              strategy="beforeInteractive"
            />
            <Suspense>
              <AnalyticsTracker user={user} />
            </Suspense>

            {children}

            <Cart />
            <SanityLive />
            <Footer />

            <Theme />
            <ScrollToTopButton />
          </ThemeContextProvider>
        </I18nProviderClient>
      </body>
    </html>
  );
};

export default RootLayout;
